# Generated by Django 4.1.5 on 2023-01-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_coord', models.FloatField(verbose_name='Первая координата')),
                ('second_coord', models.FloatField(verbose_name='Вторая координата')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.category', verbose_name='Категории')),
            ],
        ),
    ]
